# Generated by Django 5.2.7 on 2025-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nro_documento',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
